<?php

/**
 *
 * @file
 * Primary module hooks for bestlayouts module.
 */

/**
 * Implements hook_theme().
 */
function bestlayouts_theme() {
  // pre-formatage et template pour le menu.
  $hooks['layoutmenu_bestlayouts_first_menu'] = [
    'render element' => 'element',
    'preprocess functions' => [
      'template_preprocess_layoutmenu_bestlayouts_first_menu'
    ],
    'file' => 'bestlayouts.theme.inc'
  ];
  $hooks['layoutmenu_bestlayouts_dynamiques_headers'] = [
    'render element' => 'element',
    'preprocess functions' => [
      'template_preprocess_layoutmenu_bestlayouts_dynamiques_headers'
    ],
    'file' => 'bestlayouts.theme.inc'
  ];
  $hooks['bestlayouts_form_search_style_merseille'] = [
    'render element' => 'element',
    'preprocess functions' => [
      'template_preprocess_bestlayouts_form_search_style_merseille'
    ],
    'file' => 'bestlayouts.theme.inc'
  ];
  $hooks['input_submit_blm'] = [
    'render element' => 'element',
    'preprocess functions' => [
      'template_preprocess_bestlayouts_input_submit_blm'
    ],
    'file' => 'bestlayouts.theme.inc'
  ];
  $hooks['bestlayouts_login_block_icon_dropdown'] = [
    'variables' => [
      'svg_icon' => NULL,
      'entity_render' => NULL
    ]
  ];
  return $hooks;
}