# Schema for the configuration files of the bestlayouts module.
bestlayouts.settings:
  type: config_object
  label: 'bestlayouts settings'
  mapping:
    example:
      type: string
      label: 'Example'
